<script>
</script>


<div>
  <div class="row">
    <div class="col">
      <span>
        This site is used for playing dungeons generated by <a href="https://watabou.itch.io/one-page-dungeon"> Watabou's One Page Dungeon Generator</a>.<br>
        Simply create an room, upload the .json file, which contains the dungeon and copy and share the link with your friends.<br>
        As the creator of the room, you can decide which rooms your player can see. You can also spawn figures for them, which they can move.<br> <br>
        <div>
          <b> Q: The map is too big for my screen. What can I do? </b><br>
          A: You can drag the map whith the left mouse button to scroll around.<br>
          <b> Q: I scrolled to far away. How can i get back to the map? </b><br>
          A: Right click anywhere on the map and press "Reset Camera".<br>
          <b> Q: The game is just loading and does'nt seem to end. </b><br>
          A: That's because the server synchronizing your games has to wake up. Just give him some time.<br>
          <b> Q: Is there a way to make my own maps and use them? </b><br>
          A: Currently I don't know of a working way for that. Maybe I will make a tool vor that.<br>
        </div>
      </span>
    </div>
    <div class="hide-xs"> <hr class="vertical"></div>
    <div class="col">
      <b>Source</b><br>
      <span>[1] <a href="https://watabou.itch.io/one-page-dungeon"> Watabou's One Page Dungeon Generator </a></span><br>
      <b>Tools Used</b><br>
      <span>[2] <a href="https://svelte.dev"> Svelte </a></span><br>
      <span>[3] <a href="https://jenil.github.io/chota/"> chota </a></span><br>
      <span>[4] <a href="https://loading.io/animation/"> Loading.css </a></span><br>
      <span>[5] <a href="https://heroku.com/"> Heroku </a></span><br>
      <span>[6] <a href="https://www.npmjs.com/package/uuid"> uuid </a></span><br>
      <span>[7] <a href="https://www.npmjs.com/package/ws"> ws: a Node.js WebSocket library </a></span><br>
      <span>[8] <a href="https://svelte.dev/repl/79f4f3e0296a403ea988f74d332a7a4a?version=3.12.1"> Canvas 2D Game Engine </a></span><br>
      <span>[9] <a href="https://svelte.dev/repl/3a33725c3adb4f57b46b597f9dade0c1?version=3.25.0"> Context Menu </a></span><br>
    </div>
  </div>
</div>

<style>
hr.vertical {
    height:92%; /* you might need some positioning for this to work, see other questions about 100% height */
    width:0;
    border:1px solid black;
    margin-left: 10px;
    margin-right: 10px;
}
</style>
